# Generated by Django 4.2.30 on 2026-05-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
            ],
            options={
                'verbose_name': 'Composant (Menu Simplifié)',
                'verbose_name_plural': 'Composants (Menu Simplifié)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description détaillée'),
        ),
    ]
